### ISSUE TITLE
Doesn't show the name with nested subtests

### ISSUE THREAD

**Issue by C0DK** [pytest-dev/pytest-subtests#33]
When you use `subTest` nested, the label in output, is only the "deepest" label.

**example:
```
import unittest


class T(unittest.TestCase):
    def test_foo(self):
        with self.subTest("Positive Tests"):
          for i in range(5):
            with self.subTest("custom message", i=i):
                self.assertEqual(i % 2, 0)


if __name__ == "__main__":
    unittest.main()
```

**Comment by nicoddemus** [comment]
Hi @C0DK,

Thanks for the report, but it seems `unittest` also only shows the deepest label:

```
 λ python .tmp\test_sub_nested.py -v
test_foo (__main__.T) ...
======================================================================
FAIL: test_foo (__main__.T) [custom message] (i=1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".tmp\test_sub_nested.py", line 9, in test_foo
    self.assertEqual(i % 2, 0)
AssertionError: 1 != 0

======================================================================
FAIL: test_foo (__main__.T) [custom message] (i=3)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".tmp\test_sub_nested.py", line 9, in test_foo
    self.assertEqual(i % 2, 0)
AssertionError: 1 != 0

----------------------------------------------------------------------
Ran 1 test in 0.002s

FAILED (failures=2)
```

**Comment by C0DK** [comment]
Oh i was not aware that the fault is at unittest. dang. Then i'll probably just start doing it some other way.. or something. annoys me a bit though - might raise an issue at that repo then. Thanks

**Comment by nicoddemus** [comment]
I wouldn't say it is unittest's fault, but this plugin tries to mimic its behavior, so I would like to avoid deviating from the unittests's behavior too much that's all. 👍
